/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VelhaGuardaRouteImport } from './routes/velha-guarda'
import { Route as TitulosRouteImport } from './routes/titulos'
import { Route as DiretoriaRouteImport } from './routes/diretoria'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as Carnaval2026RouteImport } from './routes/carnaval-2026'
import { Route as BateriaRouteImport } from './routes/bateria'
import { Route as AEscolaRouteImport } from './routes/a-escola'
import { Route as IndexRouteImport } from './routes/index'

const VelhaGuardaRoute = VelhaGuardaRouteImport.update({
  id: '/velha-guarda',
  path: '/velha-guarda',
  getParentRoute: () => rootRouteImport,
} as any)
const TitulosRoute = TitulosRouteImport.update({
  id: '/titulos',
  path: '/titulos',
  getParentRoute: () => rootRouteImport,
} as any)
const DiretoriaRoute = DiretoriaRouteImport.update({
  id: '/diretoria',
  path: '/diretoria',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const Carnaval2026Route = Carnaval2026RouteImport.update({
  id: '/carnaval-2026',
  path: '/carnaval-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const BateriaRoute = BateriaRouteImport.update({
  id: '/bateria',
  path: '/bateria',
  getParentRoute: () => rootRouteImport,
} as any)
const AEscolaRoute = AEscolaRouteImport.update({
  id: '/a-escola',
  path: '/a-escola',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-escola': typeof AEscolaRoute
  '/bateria': typeof BateriaRoute
  '/carnaval-2026': typeof Carnaval2026Route
  '/contato': typeof ContatoRoute
  '/diretoria': typeof DiretoriaRoute
  '/titulos': typeof TitulosRoute
  '/velha-guarda': typeof VelhaGuardaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-escola': typeof AEscolaRoute
  '/bateria': typeof BateriaRoute
  '/carnaval-2026': typeof Carnaval2026Route
  '/contato': typeof ContatoRoute
  '/diretoria': typeof DiretoriaRoute
  '/titulos': typeof TitulosRoute
  '/velha-guarda': typeof VelhaGuardaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-escola': typeof AEscolaRoute
  '/bateria': typeof BateriaRoute
  '/carnaval-2026': typeof Carnaval2026Route
  '/contato': typeof ContatoRoute
  '/diretoria': typeof DiretoriaRoute
  '/titulos': typeof TitulosRoute
  '/velha-guarda': typeof VelhaGuardaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-escola'
    | '/bateria'
    | '/carnaval-2026'
    | '/contato'
    | '/diretoria'
    | '/titulos'
    | '/velha-guarda'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-escola'
    | '/bateria'
    | '/carnaval-2026'
    | '/contato'
    | '/diretoria'
    | '/titulos'
    | '/velha-guarda'
  id:
    | '__root__'
    | '/'
    | '/a-escola'
    | '/bateria'
    | '/carnaval-2026'
    | '/contato'
    | '/diretoria'
    | '/titulos'
    | '/velha-guarda'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AEscolaRoute: typeof AEscolaRoute
  BateriaRoute: typeof BateriaRoute
  Carnaval2026Route: typeof Carnaval2026Route
  ContatoRoute: typeof ContatoRoute
  DiretoriaRoute: typeof DiretoriaRoute
  TitulosRoute: typeof TitulosRoute
  VelhaGuardaRoute: typeof VelhaGuardaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/velha-guarda': {
      id: '/velha-guarda'
      path: '/velha-guarda'
      fullPath: '/velha-guarda'
      preLoaderRoute: typeof VelhaGuardaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/titulos': {
      id: '/titulos'
      path: '/titulos'
      fullPath: '/titulos'
      preLoaderRoute: typeof TitulosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diretoria': {
      id: '/diretoria'
      path: '/diretoria'
      fullPath: '/diretoria'
      preLoaderRoute: typeof DiretoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carnaval-2026': {
      id: '/carnaval-2026'
      path: '/carnaval-2026'
      fullPath: '/carnaval-2026'
      preLoaderRoute: typeof Carnaval2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bateria': {
      id: '/bateria'
      path: '/bateria'
      fullPath: '/bateria'
      preLoaderRoute: typeof BateriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-escola': {
      id: '/a-escola'
      path: '/a-escola'
      fullPath: '/a-escola'
      preLoaderRoute: typeof AEscolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AEscolaRoute: AEscolaRoute,
  BateriaRoute: BateriaRoute,
  Carnaval2026Route: Carnaval2026Route,
  ContatoRoute: ContatoRoute,
  DiretoriaRoute: DiretoriaRoute,
  TitulosRoute: TitulosRoute,
  VelhaGuardaRoute: VelhaGuardaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
